_core:
  default_config_hash: CXhei_vpaZk-3f_Mj2cH0YmpK-ZpKHoSzVA3yZrDq0g
definitions:
  contact__site_page:
    menu_name: footer
    parent: ''
    weight: 0
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:entity__node__field_ui_fieldsarticle':
    enabled: false
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.node_type.edit_form.article'
    expanded: false
    weight: 1
  'admin_toolbar_tools__extra_links:entity__entity_form_display__node__defaultarticle':
    enabled: false
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.node_type.edit_form.article'
    weight: 2
    expanded: false
  'admin_toolbar_tools__extra_links:entity__entity_view_display__node__default__article':
    enabled: false
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.node_type.edit_form.article'
    weight: 3
    expanded: false
  'admin_toolbar_tools__extra_links:entity__entity_permissions_form__node__default__article':
    enabled: false
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.node_type.edit_form.article'
    weight: 3
    expanded: false
  'admin_toolbar_tools__extra_links:entity__node_type__delete_form__article':
    enabled: false
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.node_type.edit_form.article'
    weight: 5
    expanded: false
  'admin_toolbar_tools__extra_links:entity__node__field_ui_fieldspage':
    enabled: false
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.node_type.edit_form.page'
    weight: 1
    expanded: false
  'admin_toolbar_tools__extra_links:entity__entity_form_display__node__defaultpage':
    enabled: false
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.node_type.edit_form.page'
    weight: 2
    expanded: false
  'admin_toolbar_tools__extra_links:entity__entity_view_display__node__default__page':
    enabled: false
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.node_type.edit_form.page'
    weight: 3
    expanded: false
  'admin_toolbar_tools__extra_links:entity__entity_permissions_form__node__default__page':
    enabled: false
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.node_type.edit_form.page'
    weight: 3
    expanded: false
  'admin_toolbar_tools__extra_links:entity__node_type__delete_form__page':
    enabled: false
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.node_type.edit_form.page'
    weight: 5
    expanded: false
  'admin_toolbar_tools__extra_links:entity__media__field_ui_fieldsaudio':
    enabled: false
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.media_type.edit_form.audio'
    weight: 1
    expanded: false
  'admin_toolbar_tools__extra_links:entity__entity_form_display__media__defaultaudio':
    enabled: false
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.media_type.edit_form.audio'
    weight: 2
    expanded: false
  'admin_toolbar_tools__extra_links:entity__entity_view_display__media__default__audio':
    enabled: false
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.media_type.edit_form.audio'
    weight: 3
    expanded: false
  'admin_toolbar_tools__extra_links:entity__entity_permissions_form__media__default__audio':
    enabled: false
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.media_type.edit_form.audio'
    weight: 3
    expanded: false
  'admin_toolbar_tools__extra_links:entity__media_type__delete_form__audio':
    enabled: false
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.media_type.edit_form.audio'
    weight: 5
    expanded: false
  'admin_toolbar_tools__extra_links:entity__media__field_ui_fieldsdocument':
    enabled: false
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.media_type.edit_form.document'
    weight: 1
    expanded: false
  'admin_toolbar_tools__extra_links:entity__entity_form_display__media__defaultdocument':
    enabled: false
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.media_type.edit_form.document'
    weight: 2
    expanded: false
  'admin_toolbar_tools__extra_links:entity__entity_view_display__media__default__document':
    enabled: false
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.media_type.edit_form.document'
    weight: 3
    expanded: false
  'admin_toolbar_tools__extra_links:entity__entity_permissions_form__media__default__document':
    enabled: false
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.media_type.edit_form.document'
    weight: 3
    expanded: false
  'admin_toolbar_tools__extra_links:entity__media_type__delete_form__document':
    enabled: false
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.media_type.edit_form.document'
    weight: 5
    expanded: false
  'admin_toolbar_tools__extra_links:entity__media__field_ui_fieldsimage':
    enabled: false
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.media_type.edit_form.image'
    weight: 1
    expanded: false
  'admin_toolbar_tools__extra_links:entity__entity_form_display__media__defaultimage':
    enabled: false
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.media_type.edit_form.image'
    weight: 2
    expanded: false
  'admin_toolbar_tools__extra_links:entity__entity_view_display__media__default__image':
    enabled: false
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.media_type.edit_form.image'
    weight: 3
    expanded: false
  'admin_toolbar_tools__extra_links:entity__entity_permissions_form__media__default__image':
    enabled: false
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.media_type.edit_form.image'
    weight: 3
    expanded: false
  'admin_toolbar_tools__extra_links:entity__media_type__delete_form__image':
    enabled: false
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.media_type.edit_form.image'
    weight: 5
    expanded: false
  'admin_toolbar_tools__extra_links:entity__media__field_ui_fieldsremote_video':
    enabled: false
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.media_type.edit_form.remote_video'
    weight: 1
    expanded: false
  'admin_toolbar_tools__extra_links:entity__entity_form_display__media__defaultremote_video':
    enabled: false
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.media_type.edit_form.remote_video'
    weight: 2
    expanded: false
  'admin_toolbar_tools__extra_links:entity__entity_view_display__media__default__remote_video':
    enabled: false
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.media_type.edit_form.remote_video'
    weight: 3
    expanded: false
  'admin_toolbar_tools__extra_links:entity__entity_permissions_form__media__default__remote_video':
    enabled: false
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.media_type.edit_form.remote_video'
    weight: 3
    expanded: false
  'admin_toolbar_tools__extra_links:entity__media_type__delete_form__remote_video':
    enabled: false
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.media_type.edit_form.remote_video'
    weight: 5
    expanded: false
  'admin_toolbar_tools__extra_links:entity__media__field_ui_fieldsvideo':
    enabled: false
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.media_type.edit_form.video'
    weight: 1
    expanded: false
  'admin_toolbar_tools__extra_links:entity__entity_form_display__media__defaultvideo':
    enabled: false
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.media_type.edit_form.video'
    weight: 2
    expanded: false
  'admin_toolbar_tools__extra_links:entity__entity_view_display__media__default__video':
    enabled: false
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.media_type.edit_form.video'
    weight: 3
    expanded: false
  'admin_toolbar_tools__extra_links:entity__entity_permissions_form__media__default__video':
    enabled: false
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.media_type.edit_form.video'
    weight: 3
    expanded: false
  'admin_toolbar_tools__extra_links:entity__media_type__delete_form__video':
    enabled: false
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.media_type.edit_form.video'
    weight: 5
    expanded: false
  'admin_toolbar_tools__extra_links:entity__taxonomy_vocabulary__edit_form__tags':
    enabled: false
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.taxonomy_vocabulary.overview_form.tags'
    weight: 0
    expanded: false
  'admin_toolbar_tools__extra_links:entity__taxonomy_term__field_ui_fieldstags':
    enabled: false
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.taxonomy_vocabulary.overview_form.tags'
    weight: 1
    expanded: false
  'admin_toolbar_tools__extra_links:entity__entity_form_display__taxonomy_term__defaulttags':
    enabled: false
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.taxonomy_vocabulary.overview_form.tags'
    weight: 2
    expanded: false
  'admin_toolbar_tools__extra_links:entity__entity_view_display__taxonomy_term__default__tags':
    enabled: false
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.taxonomy_vocabulary.overview_form.tags'
    weight: 3
    expanded: false
  'admin_toolbar_tools__extra_links:entity__entity_permissions_form__taxonomy_term__default__tags':
    enabled: false
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.taxonomy_vocabulary.overview_form.tags'
    weight: 3
    expanded: false
  'admin_toolbar_tools__extra_links:entity__taxonomy_vocabulary__delete_form__tags':
    enabled: false
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.taxonomy_vocabulary.overview_form.tags'
    weight: 5
    expanded: false
  'admin_toolbar_tools__extra_links:views_ui__archive':
    enabled: false
    menu_name: admin
    parent: entity.view.collection
    weight: 0
    expanded: false
  'admin_toolbar_tools__extra_links:views_ui__glossary':
    enabled: false
    menu_name: admin
    parent: entity.view.collection
    weight: 0
    expanded: false
  'admin_toolbar_tools__extra_links:views_ui__user_admin_people':
    enabled: false
    menu_name: admin
    parent: entity.view.collection
    weight: 0
    expanded: false
  'admin_toolbar_tools__extra_links:views_ui__content_recent':
    enabled: false
    menu_name: admin
    parent: entity.view.collection
    weight: 0
    expanded: false
  'admin_toolbar_tools__extra_links:views_ui__taxonomy_term':
    enabled: false
    menu_name: admin
    parent: entity.view.collection
    weight: 0
    expanded: false
  'admin_toolbar_tools__extra_links:views_ui__watchdog':
    enabled: false
    menu_name: admin
    parent: entity.view.collection
    weight: 0
    expanded: false
  'admin_toolbar_tools__extra_links:views_ui__who_s_new':
    enabled: false
    menu_name: admin
    parent: entity.view.collection
    weight: 0
    expanded: false
  'admin_toolbar_tools__extra_links:views_ui__who_s_online':
    enabled: false
    menu_name: admin
    parent: entity.view.collection
    weight: 0
    expanded: false
  system__admin_config_services:
    enabled: false
    menu_name: admin
    parent: system.admin_config
    weight: 0
    expanded: false
  system__rss_feeds_settings:
    enabled: false
    menu_name: admin
    parent: system.admin_config_services
    weight: 0
    expanded: false
  system__admin_config_workflow:
    enabled: false
    menu_name: admin
    parent: system.admin_config
    weight: 5
    expanded: false
