_core:
  default_config_hash: AXUBMTvVtpcNp0jKjDaWjSHqMy6HjuUf7j4yVbXgazI
local_task_enabled_entity_types:
  - block
  - block_content
  - image_style
  - media
  - node
  - taxonomy_term
  - view
track_enabled_source_entity_types:
  - block
  - node
  - block_content
  - field_config
  - file
  - image_style
  - media
  - taxonomy_term
  - view
track_enabled_target_entity_types:
  - block
  - node
  - block_content
  - field_config
  - file
  - image_style
  - media
  - taxonomy_term
  - view
track_enabled_plugins:
  - block_field
  - dynamic_entity_reference
  - entity_embed
  - entity_reference
  - html_link
  - layout_builder
  - link
  - linkit
  - media_embed
track_enabled_base_fields: false
site_domains: {  }
edit_warning_message_entity_types: {  }
delete_warning_message_entity_types:
  - block
  - node
  - block_content
  - field_config
  - file
  - image_style
  - media
  - taxonomy_term
usage_controller_items_per_page: 25
